export const FETCH_PRODUCTDETAILS_REQUEST = "FETCH_PRODUCTDETAILS_REQUEST";
export const FETCH_PRODUCTDETAILS_SUCCESS = "FETCH_PRODUCTDETAILS_SUCCESS";
export const FETCH_PRODUCTDETAILS_FAILURE = "FETCH_PRODUCTDETAILS_FAILURE";
export const CLEAR_PRODUCTDETAILS = "CLEAR_PRODUCTDETAILS";
